linters:
  # disable-all: true
  # enable:
  #  - testifylint
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - copyloopvar
    - depguard
    - dupl
    - errcheck
    - execinquery
    - exhaustruct
    - err113
    - forbidigo
    - gomnd
    - intrange
    - ireturn
    - misspell
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
linters-settings:
  mnd:
    ignored-numbers:
      - '0b0'
      - '0b1'