linters:
  # disable-all: true
  # enable:
  #  - testifylint
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - depguard
    - dupl
    - execinquery
    - exhaustruct
    - forbidigo
    - gci
    - goerr113
    - misspell
    - paralleltest
    - structcheck
    - testpackage
    - varnamelen
    - wsl

    # Disable noisy linters
    - ireturn

    # Disable deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - varcheck

linters-settings:
  cyclop:
    max-complexity: 15
  gocritic:
    disabled-checks:
      - dupSubExpr
  gomnd:
    ignored-numbers:
      - '0b0'
      - '0b1'
      - 2
  lll:
    line-length: 150
  mnd:
    ignored-numbers:
      - '0b0'
      - '0b1'
issues:
  max-issues-per-linter: 50
  max-same-issues: 50
  exclude-rules:
    - path: ./*_test\.go
      linters:
        - errcheck