linters:
  # disable-all: true
  # enable:
  #  - testifylint
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - depguard
    - dupl
    - errcheck
    - exhaustruct
    - forbidigo
    - goerr113
    - gomnd
    - ireturn
    - misspell
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
